microsoft/ConversationLearner-SDK

package-lock.json
package.json
src/CLRunner.ts

See: https://github.com/Microsoft/ConversationLearner-Samples/issues/193

1350: History returns terminal state of last action

---

package-lock.json
package.json

Updated packages.json to use the latest version of botbuilder and @conversationlearner/ui

Updated packages.json

---

src/CLDebug.ts
src/CLRunner.ts
src/Memory/ClientMemoryManager.ts

Bug: Failing to restore memory after callback
Bug: Prebuilts are not LOCAL and LUIS

1357: API callback not keeping entity values

---

.circleci/config.yml
appveyor.yml
package-lock.json

Remove bbnpm references from package-lock.json introduced in #261

 Add appveyor.yml and .circleci/config.yml

---

src/utils.test.ts

- Add test for addEntitiesById (Not really new feature but want to test semantic-release)

feat: fake feature to test semantic release

---

README.md
package-lock.json
package.json
src/CLRunner.ts

* ci: set breaking release type to minor
BREAKING CHANGE: Change CONVERSATION_LEARNER_APP_ID to CONVERSATION_LEARNER_MODEL_ID

 refactor(env): change _APP_ID to _MODEL_ID

---

package-lock.json
package.json
src/CLClient.ts

- update models and ui packages
- update client to return entire server response

fix: allow negative entity creation in single call

---

package-lock.json
package.json
src/CLRunner.ts
src/ConversationLearner.ts
src/Http/Server.ts
src/Memory/BotMemory.ts
src/Memory/BotState.ts

Added EndSession Action and re-worked onSessionEnd / onSessionStart apis

1377 end session action

---

src/clUi.ts

added more explanatory message for port in use as was confusing some users

fix: added more explanatory message for port in use

---

package-lock.json
src/CLDebug.ts
src/CLRunner.ts
src/Memory/BotMemory.ts
src/Memory/ClientMemoryManager.ts

feat: show clDebug errors in chat window 1241
feat: show error message if memoryManager values are set after callback has returned 1367

feat: debug errors in chat log & memoryManager error on set after callback returned

---

src/CLDebug.ts

Added highlights to errors in log:

fix: highlight log errors in chat window

---

package-lock.json
package.json
src/CLClient.ts

Had talked to Lars about this a while back. It was added long time ago (9 months) and intended to be removed but left in a few places.  The UI already has them in memory so this was obsolete

fix: remove node cache

---

package-lock.json
package.json
src/CLMemory.ts
src/CLRunner.ts
src/Http/Server.ts
src/Memory/BotMemory.ts
src/Memory/BotState.ts

- fix: sessions starting with wrong Id
- fix: orgSessionId set on sessionEnd not sessionStart
- fix: expire session was ingoring orgSessionId
- style: rename function to note async
- style: rename fuctiuon with hidden side effect for clarity

 fix: session management

---

package-lock.json
package.json
src/CLRunner.ts
src/ConversationLearner.ts
src/Http/Server.ts
src/Memory/BotState.ts
src/Memory/ClientMemoryManager.ts
src/Utils.ts
src/index.ts

feat: OnSessionEndCallback gets SessionEndState
style: Replaced "UIRunner" string instances with UI_RUNNER_APPID const
style: Rename SetOnSessionCalled to SetNeedSessionEndCall for better clarity
style: added comments
feat: update models and UI package

feat: sessionendstate

---

package-lock.json
package.json
src/Http/Server.ts

There were some incorrect requests being made which caused errors during action editing.

 fix: action editing

---

package-lock.json
package.json

new UI has local storage load fix

fix: update ui

---

package-lock.json
package.json

fix: conersationid not set

---

src/http/router.ts

Change to prevent two calls to end session

fix: log dialog end after endsession action

---

src/FileStorage.ts

Is a legitimate occurance.  Don't show error message in log

fix: missing file error Mutex

---

src/CLRunner.ts
src/Memory/BotState.ts
src/http/router.ts

Change ISessionStartParams to SesssionStartFlags

fix: orgsessionid not being cleared out on manual timeout

---

src/CLRunner.ts
src/Utils.ts

Console was just showing 500, with no info

fix: catch permissions error

---

package-lock.json
package.json

fix: update ui package

---

package-lock.json
package.json
src/CLRunner.ts
src/ConversationLearner.ts
src/http/router.ts

Necessary for multi-cl apps
Get bot info takes appId

fix: intrainingui checks appid

---

package-lock.json
package.json
src/CLRunner.ts
src/ConversationLearner.ts
src/http/router.ts

Update `GetHistory` to only invoke the render fn of the of callback definition.

 fix: update apiAction to return object with logicResult and response

---

package-lock.json
package.json
src/CLRunner.ts
src/http/router.ts

Now that LogicResult is saved as a string we must use JSON.stringify on objects to save and JSON.parse when consuming from database/

fix: use json stringify and json parse on logic result

---

package-lock.json
package.json
src/CLRunner.ts

Update UI version for rich log editing
Add new replay error type to capture unfilled entities

feat: log rich edit

---

package-lock.json
package.json

fix: ui bugs

---

package-lock.json
package.json
src/CLRunner.ts

feat: down arrow

---

package-lock.json
package.json
src/Memory/BotMemory.ts
src/Memory/BotState.ts

feat: team channel fix

---

src/CLRunner.ts

Render callback gives the wrong error when I edit memory in it

fix: bug 1501

---

package-lock.json
package.json
src/CLClient.ts
src/http/router.ts

Handle label extraction conflicts

feat: extract conflicts

---

package-lock.json
package.json
src/CLClient.ts
src/http/router.ts

filter current dialog out when checking for label conflicts

fix: conflict filters

---

package-lock.json
package.json
src/CLClient.ts
src/CLRunner.ts
src/http/router.ts

fix: package version and chat

---

package-lock.json
package.json

feat: resolver type

---

src/CLClient.ts
src/CLRunner.ts

- resolve the issue with number of changed filled entities
- fix logic result posted to update session api

fix: resolve the issue with number of changed filled entities

---

src/Memory/ClientMemoryManager.ts

- Make converter optional for Get<T>
- Fix Delete for entities that are not multivalue

feat: make converter optional on memory managet get

---

src/Memory/ClientMemoryManager.ts

- Fix Delete issue
- Add DeleteAll() 
- Change Get to return MemoryValue for single value entities and MemoryValue[] for multivalue entities

feat: return memoryvalue for non-multivalue entities

---

package-lock.json
package.json

feat: extractor test support

---

package-lock.json
package.json
src/CLDebug.ts
src/CLRunner.ts
src/index.ts

fix: export memoryvalue

---

package-lock.json
package.json
src/CLRunner.ts

feat: release candidate

---

package-lock.json
package.json
src/TemplateProvider.ts

feat: buttons data uses text not object

---

package-lock.json
package.json
src/Utils.ts

fix: handle null logicAPIresult

---

appveyor.yml

Should only build PR's targeting master and NOT build pushes to branches

chore: change appveyor.yml to be consistent with others

---

package-lock.json
package.json

In preparation for bug bash we want to make sure samples is running the latest code.

fix: update UI and models packages

---

src/http/router.ts

Seems the `HandleError` function hasn't been updated in a while and was stripping off the `reason` data from server. When it's a conflict it is allowed to be returned so the UI can display conflicts.
These differ from other situations in which the SDK needed to return session data + errors during replay. In this case the errors came from the server instead of SDK so it's more appropriate to keep the server as source of truth.

fix: allow server to return conflict information

---

src/CLClient.ts
src/CLRunner.ts
src/FileStorage.ts

Similar to the UI PR. https://github.com/Microsoft/ConversationLearner-UI/pull/998
Mostly affects code around the asynchronous file operations. Will need to test a before completing but at least idea is there.

fix: use async where possible

---

package-lock.json
package.json

feat: update ui

---

src/FileStorage.ts

Turns the inner functions of the loops which were async function back into promise chains.  Seems to fix the issue with log dialogs not receiving input and some exception being thrown.
I'm still not quite sure what the difference is since before and after the change it still allows the promises to complete in any order and waits for them to all complete.  Probably some weird race condition with file access

fix: remove async from inner functions

---

package-lock.json
package.json

- merging of dialogs
- allow tags and descriptions on log dialogs
- on dialog lists show user input list rather than just first / last

feat: update ui for merge, dialog list and tag description updates

---

package-lock.json
package.json

Bring in latest UI before release

fix: update ui to 0.352.19

---

package-lock.json
package.json
src/CLRunner.ts

Calculation of intialFilledEntities now done and log conversion time

fix: bug 2076 issue with onSessionEnd and intitialFilledEntities

---

package-lock.json
package.json

fix: sdk to 0.353.21

---

package-lock.json
package.json

fix: use radio button for action delete type

---

package-lock.json
package.json
src/CLRunner.ts
src/Memory/BotMemory.ts

Hope to merge this into samples so Swadheen can test the new entity types

 fix: update dependencies

---

src/Memory/BotState.ts

Create PR for temp release. Have to look up conventions for package naming.
Thinking it will be like `0.319.7-conversationid`

feat: add conversationId to SessionInfo object

---

src/CLClient.ts

was trying to debug schema validation issues and was confused by this, turns out it's not used anymore

fix: remove unused path

---

package-lock.json
package.json
src/CLRunner.ts

fix: bug 2202 render error on session actions

---

.vscode/launch.json

Removes old launch configs no longer used.

chore: remove old launch config

---

package-lock.json
package.json
src/CLModelOptions.ts
src/CLRunner.ts
src/http/router.ts

also lowered re-prompt threshold

fix: handle wait non-wait properly in testing

---

package-lock.json
package.json
src/CLRunner.ts
src/http/router.ts

Update UI package to one with history changes
Change the fromhistory routes to fromtraindialog

 fix: fromhistory fromtraindialog

---

package-lock.json
package.json

feat: add resolution required option to entities

---

.vscode/settings.json
package-lock.json
package.json
src/CLClient.ts
src/CLRunner.ts
src/FileStorage.ts
src/Memory/BotState.ts
src/Memory/ClientMemoryManager.ts
src/Memory/InputQueue.ts
src/TemplateProvider.ts
src/Utils.ts
src/http/router.ts
src/uiServer.ts
tsconfig.json

Similar to https://github.com/microsoft/ConversationLearner-UI/pull/1362

fix: use optional chaining and null coalescing where possible

---

package-lock.json
package.json

fixes action scorer entity substitution

fix: ui to 0.413.7

---

src/CLRunner.ts

Not sure this is the source of the error but trying it

fix: null stack
