- src/CLRunner.ts
- src/ConversationLearner.ts
- src/Memory/BotMemory.ts
- src/Memory/BotState.ts
- tsconfig.json
Make sure variables have proper initiation and can't be accessed when they are possibly undefined.
> fix: enable strict checks for typescript compilation

- src/CLClient.ts
- src/Http/Server.ts
Previously there were messages like:
```
Tue, 03 Jul 2018 21:20:53 GMT express deprecated res.send(status): Use res.sendStatus(status) instead at ..\cl-sdk\lib\Http\Server.js:115:17
```
This should fix those by properly using `sendStatus`
Also, normalize how we get parameters from `req.params` to single line.
Use `const` instead of `let` where possible
> fix: remove deprecations and use desctructuring for params

- src/Http/Server.ts
There is bug during page refresh when UI is still on app page it will call `/state/app` when the component renders.  It will detects no app in the state and redirect back to homepage to call /botinfo and get a userid / memory key; however, it is too late. The call has already been made and it will show the error panel which blocks the app since the /state/app request fails without memory key header.
> fix: allow undefined mem key for /state/app

- src/http/router.ts
I think we need to make this stuff configurable from the samples, but for now will disable to avoid confusion from users.
Fixes VSTS#1436
> fix: change log level to info

- src/CLRunner.ts
- src/Memory/BotMemory.ts
allows developers to not return anything instead of having to explicitly return `undefined` which is unnatural as undefined is implied with no return value.
> fix: change return type of OnSessionEndCallback to allow void

- src/CLRunner.ts
- src/ConversationLearner.ts
- src/http/router.ts
style: rename appId to configModelId for clarity
style: remove appId from clClient as not needed
fix: configModelId being overwritten when run UI in parallel emulator
fix: ignore conversation updates earlier in processing a message
fix: remove duplicate error message display
style: rename get to getRunnerForUI for usage clarity
>  fix: changing ui app can impact emulator

- src/CLMemory.ts
- src/CLRunner.ts
- src/Memory/BotState.ts
fix: Reordered ProcessInput loop to better handle changing of modelId mid-flight when bot is running
fix: 403 error was displaying at 500 in UI (try catch around endSessionasync)
fix: prevent double error message display
> fix: changing modelId while in emulator

- src/CLRunner.ts
Fixed edge case where swiching .env file Model while running in emulator could end up with CL choosing the previously picked Model
> fix: wrong app possible in hybrid bot

- src/AzureFunctions.ts
- src/CLClient.ts
- src/CLDebug.ts
- src/CLMemory.ts
- src/CLOptions.ts
- src/CLRecognizeResult.ts
- src/CLRunner.ts
- src/ConversationLearner.ts
- src/FileStorage.ts
- src/Memory/BotMemory.ts
- src/Memory/BotState.ts
- src/Memory/BrowserSlot.ts
- src/Memory/ClientMemoryManager.ts
- src/Memory/InputQueue.ts
- src/RedisStorage.ts
- src/TemplateProvider.ts
- src/Utils.ts
- src/clUi.ts
- src/clUiRunner.ts
- src/constants.ts
- src/http/router.test.ts
- src/http/router.ts
- src/index.ts
- src/utils.test.ts
There is current bug with syntax highlighting on TypeScripot files which have trailing white space.
https://github.com/Microsoft/TypeScript-TmLanguage/issues/654
https://github.com/Microsoft/vscode/issues/56706#issuecomment-414385756
> style: remove trailing white space

- src/upgrade.test.ts
Forgot to format the name of the PR during last squash and want to trigger auto-release. Also adding another test.
> fix: add test for changed app

- package-lock.json
- package.json
- src/CLRunner.ts
- src/upgrade.test.ts
- Adds new `TakeSetEntityAction` similar to the `TakeTextAction` and `TakeAPIAction`
- Uses the new `ReplaySetEntityException` for errors during this.
- Use proper discriminated union on `IActionInput`
When taking the action during teaching it displays a placeholder card similar to the API actions.
I chose the text `memory.Set(entityName, VALUE)` hoping to show the users what the affect of taking the action is doing to the memory and how they could simulate it within API callbacks if they wanted to do it themselves.  Open to more ideas though. 
Cons that I see are too technical, or takes up two much vertical space.
Could remove the card title or text to consolidate although if we do it for this type we should probably do it for the rest.
> feat: add set entity actions

- package-lock.json
- package.json
- src/http/router.ts
Guess I missed this one in previous clean up. Allows client to send `excludeConverted` parameter
> fix: remove unnecessary interception

- src/CLClient.ts
Fix the 404 Resource Not Found error due to #441 which stopped sending the parameter when false.
> fix: always send saveDialog parameter

- src/CLRunner.ts
- src/Memory/BotState.ts
When the channel is msteams the CONVERSATION_ID is set to an object instead of a string.
Somehow we had code that compared the user.id to the conversationId. There must have been a bug previously where Teams client was storing this id in the user object.
They must have fixed their code to store it in the proper conversation object and this updates our code accordingly to match.
Also adds typing information. I made the seeming Microsoft specific properties like `tenantId` and `aadObjectId` nullable for other channel that won't have them.
But I assume all users and bots will have an id and name.
> fix: get conversation id from conversation object in msteams

- src/CLRunner.ts
- src/Memory/BotState.ts
I wasn't aware of types from `botbuilder-js` instead of adding our own.
Talked with Shahin about #459. He had some comments in a review but didn't submit the review so I didn't see them and had already merged thinking it was settled.
There are larger concerns about using conversation references and extracting conversation id string from them instead of storing these ids separately and comparing differently typed objects, but this simple type change is good for start.
> fix: use types from BotBuilder

- .circleci/config.yml
Similar to https://github.com/microsoft/ConversationLearner-Models/pull/186  
I had only updated the config to 2.1 on the UI and going to do it for models and SDK to leverage auto canceling feature. Also will mke it only build PR's
> build: update config to 2.1 for canceling redundant builds

- package-lock.json
- src/CLClient.ts
Allows passing an object to the `MakeUrl` function and using the `querystring` module from node to generate the string.  This is easier to manage and less error prone.  
Still allows taking strings because in some cases we forward the query string from the UI
Fixes ADO#1143
>  fix: use object for querystring generation

- src/CLDebug.ts
The cache is in place to cover logs/errors that are triggered before the adpater is set (i.e. a brand new conversation).  Now it checks that the same conversationReference is set, so messages don't leak from one conversation to another.  However, this means that there's a rare case where an error message at conversation start could never get sent.
> fix: bug 2181 dubug messages leaking to wrong conversation

- src/CLRunner.ts
GetRunningApp was using turn context to get instance of memory but not returning the instance.
Then immediatly after this call another instance would be created.
Changes to create instance and pass to GetRunningApp
> fix: pass memory to GetRunningApp instead of initializing twice

- src/CLDebug.ts
- src/CLMemory.ts
- src/CLRunner.ts
- src/Memory/BotState.ts
- src/Memory/InProcessMessageState.ts
- src/Memory/InputQueue.ts
This is minimal change to get dispatch actually working in the logs so it can be tested. After a few debug sessions with Lars we have more changes planned.
When in training the bot returns the action the dispatcher model takes which is (What model to dispatch to?)
When in logs the bot recursively delegates to the subModels until an action on one of the leaf model is reached and this is returned.
Usages depends on generation of model/actions using UI feature. It currently generates text actions with special encoding to indicate they are dispatch actions but should introduce new action type in future.
Technical Changes:
- Detection of Dispatch action (Encoding of text actions)
- Splitting out the MessageState tracking from BotState to allow independent CLMemory intances with different keys. …
>  feat: enable dispatching to sub models

- package-lock.json
- package.json
- src/CLRunner.ts
depends on UI generating these actions since they can't be manually created or edited.
Updates the `GetHistory` function to return the card placeholders similar to the SET_ENTITY actions.
> feat: use DISPATCH action type instead of overloaded TEXT action

- .vscode/settings.json
- package-lock.json
- src/ConversationLearner.ts
Change EDC to assignment.
Fixes issue Thomas ran into and makes API better explain implementation.
- overwrites
- clear only last function is used
- can only be one
> feat: make EDC assignment instead of function

- package-lock.json
- package.json
- src/CLRunner.ts
- src/Utils.ts
There was bug with conditions not being re-computed when fetching the dialog activities.
This fixes the bug for existing EnumConditions and also adds support for upcoming ValueConditions.
Can see when changing label from "2" (number which means low condition) to "80" number no longer satisfying the low condition and error shown.
> fix: recompute action conditions when fetching dialog activities

- package-lock.json
- package.json
- src/CLRecognizeResult.ts
- src/CLRunner.ts
- src/CLStrings.ts
- src/ConversationLearner.ts
- src/Memory/CLState.ts
- src/Memory/InputQueue.ts
- src/http/router.ts
- Ensure all instantiated models are put in model cache by making it part of construction instead of explicit addition.
- Add `ConversationModelState` to store which model is active for conversation.
- Consolidate placeholder card renderings for actions that have no visual effect on dialog.
- Fix what looks to be bug with not storing `turnContext`
> feat: add support for CHANGE_MODEL actions

- src/ConversationLearner.ts
Lars had mentioned breaking changes in chat and reminded me to do this.
EntityDetectionCallback was changed to be assignment to better express how the code works but I should have changed them all. This PR should make all the single model specific callbacks assignment.
The code callbacks for actions are still left as method since you can have many.
Do you see any thing I missed?  Would rather have one breaking change than two.
> fix: make callback assignment consistent

- src/CLClient.ts
- src/CLRunner.ts
- src/Memory/BotState.ts
- src/Memory/CLState.ts
- src/Memory/InputQueue.test.ts
- src/Memory/InputQueue.ts
When we refactored the memory we switched to using a conversationId scoped mutex but were still using a shared queue which caused multi-conversations to run into issues.   Fixed the bug and also took opportunity to clean it up a bit and add tests.  
Note queue is still in-memory so won't work for multi-host bots.  See ADO 2412
> fix: bug 2417 multi-conversation message queuing
